version: 1.1.{build}
image: Visual Studio 2017
branches:
  only:
  - master
clone_depth: 1
init:
  # Good practise, because Windows
  - git config --global core.autocrlf true
before_build:
  # Display minimal restore text
  - cmd: dotnet restore --verbosity m
build_script:
  # output will be in ./src/bin/Release/netcoreapp2.0/publish/
  - cmd: dotnet publish -c Release
test_script:
  # tests in here
  - cmd: cd tests
  - cmd: dotnet xunit
artifacts:
 - path: '\src\bin\Release\netcoreapp2.0\publish'
   name: WebSite
   type: WebDeployPackage
deploy:
- provider: Environment
  name: dwCheckApi-Production