version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  #- cd src
  # Display .NET Core version
  - cmd: dotnet --version
  # Display normal restore text
  #- dotnet restore ./src/src.csproj
  # Display minimal restore text
  - cmd: dotnet restore ./src/src.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./src/src.csproj
  #project: .\src\src.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: '\src\bin\Debug\netcoreapp1.1\publish'
   name: WebSite
   type: WebDeployPackage
clone_depth: 1
test_script:
  # tests in here
  - cmd: dotnet restore ./tests/tests.csproj --verbosity m
  - cmd: cd tests
  - cmd: dotnet xunit
  - cmd: cd ..
on_finish :
  # any cleanup in here
deploy: off
