version: '2.0.alpha-{build}'
image: Visual Studio 2017
branches:
  only:
  - master
clone_depth: 1
init:
  # Good practise, because Windows
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  #- cd src
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore --verbosity m
build_script:
  # output will be in ./src/bin/Release/netcoreapp2.0/publish/
  - cmd: dotnet publish -c Release
after_build:
  # For once the build has completed
test_script:
# tests in here
- cmd: cd tests
- cmd: dotnet xunit
artifacts:
 - path: '\src\bin\Release\netcoreapp2.0\publish'
   name: WebSite
   type: WebDeployPackage
on_finish :
  # any cleanup in here
deploy: off
