version: 1.0.{build}
install:
- cmd: >-
    dotnet restore
    npm install -g bower
build:
  verbosity: minimal
after_build:
- cmd: dotnet publish src\CoreWebApplication1 --output %appveyor_build_folder%\dist
artifacts:
- path: dist
  name: dist.web